### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by JoseSoteloCohen** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#9]
Look for ways to change the icon with the default widget

**Comment by MrJoax** [comment]
Hi 👋 

It would be great if I could switch to the plugin logo on Wordpress.org instead of that moon.. the logo is super clear I think 👍🏼 And maybe let the widget switch to white when darkmode is active.

Great plugin btw 🙂 looks like I can adapt most stuff that doesn’t work right of the bat with the body class

I’m working on my new site here https://www.arendmaatkamp.nl/

**Comment by JoseSoteloCohen** [comment]
@MrJoax 

By default, the field for the icon is text, so you could only use an emoji, but I'm about to release 2.0.0, which will allow you to use anything with the class "darkmode-enable" as the widget toggle.

So now you can create your widget or maybe add an icon in your header to enable/disable dark mode, or even text.
